# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\x12\x04grpc\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x04Msje\x12\x0f\n\x07message\x18\x01 \x01(\t22\n\nContection\x12$\n\x07SendMsg\x12\r.grpc.Request\x1a\n.grpc.Msjeb\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='grpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpc.Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=43,
)


_MSJE = _descriptor.Descriptor(
  name='Msje',
  full_name='grpc.Msje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.Msje.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Msje'] = _MSJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Request)
  })
_sym_db.RegisterMessage(Request)

Msje = _reflection.GeneratedProtocolMessageType('Msje', (_message.Message,), {
  'DESCRIPTOR' : _MSJE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Msje)
  })
_sym_db.RegisterMessage(Msje)



_CONTECTION = _descriptor.ServiceDescriptor(
  name='Contection',
  full_name='grpc.Contection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=70,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='grpc.Contection.SendMsg',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_MSJE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTECTION)

DESCRIPTOR.services_by_name['Contection'] = _CONTECTION

# @@protoc_insertion_point(module_scope)
