version: "3"

services:
  server:
    build: server/

    command: python3 server.py

    volumes:
      - ./server:/server/

    ports:
      - 5000:5000

  client:
    build: client/

    command: tail -f /dev/null

    volumes:
      - ./client:/client/

    depends_on:
      - server
